# Religion {#sec-rulebook-religion}

Religion (nicht im klassischen Sinne) ist wichtig für hochintelligente Wesen, auch wenn es keine Götter gibt,
um mit der Tatsache, dass eigentlich alles egal ist, umgehen zu können.
Sie füllt sozusagen die Wissenslücke zur Existenzbegründung des Universums.

## Abgrenzung

Es ist wichtig, den Ursprung und damit die Grenzen der Religion zu verstehen.

### Der Glaube

Menschen lieben Geschichten.
Geschichten kann man sich besser merken als Fakten.
Daher ist es raffiniert, sich Geschichten auszudenken, die die Menschen gerne erzählen.
Die christliche Bibel, der islamische Koran, die griechischen, ägyptischen und römischen Mythologien.
Das alles sind Geschichten.
Natürlich mögen sie teilweise moralisch wertvolle Leitsätze enthalten:
Als Teil der Kultur leiten sie - mehr oder weniger bewusst - 
das eigene Leben und den Umgang mit anderen Menschen.
Damals, als sie verfasst wurden, wurden sie für richtig erachtet;
oder es war für die Herrschenden praktisch, wenn sich das allgemeine Volk nach ihnen gerichtet hatte.

Aber als seriöse Grundlage für eine moderne Gesellschaft
dürfen diese Geschichten nicht ohne Weiteres herangezogen werden.

### Die Kirche

Die Kirche verfolgt eigentlich zwei Ziele:

Zum einen ist sie eine Gemeinschaft für Gläubige, um die Religion zu leben und zu verbreiten.
Leider lässt man sich von den Geschichten leicht blenden bzw. nimmt sie zu ernst,
wodurch klassische Ideologien bestärkt werden.

Zum anderen bietet die Kirche humanitäre und karitative Leistungen an,
womit ihre Existenz oft gerechtfertigt wird.
Allerdings ist die Kopplung mit dem religiösen Aspekt historisch bedingt und keine logische Implikation.
