# Supera Specios {#sec-implementation-supera-specios}

Das _Specios_ definiert zum einen den grundlegenden ideologischen Rahmen,
in dem sich die Gesellschaft bewegen kann.
Dazu gehört insbesondere, dass der Mensch nicht per-se in den Mittelpunkt gestellt wird.
Es gibt klare Regeln, um mit der Umwelt im Einklang leben zu können.
Das Ziel ist es stets, das Wohlbefinden aller Lebewesen zu maximieren,
unter Einhaltung gewissen Rahmenbedingungen.

Darauf aufbauend können sogenannte _Supera Specios_ geschaffen werden,
die sich kompromisslos an die Regeln des Specios halten müssen
und den politischen und gesetzlichen Rahmen für eine spezifische Gesellschaft schaffen.

Wie ein solches Supera Specios aussehen könnte, werden wir nun skizzieren.

## Grundlegende Ideen des Specios

Wie auf den ersten Seiten bereits beschrieben,
wird die Gesellschaft mit Specios komplett neu gedacht -
frei von unbegründeten Altlasten^[
Mit Altlasten meinen wir Dinge wie religiöse Schriften oder kulturelle Eigenheiten/Normen.
].

Das Wertesystem und die Regeln werden aus wenigen gut begründeten Grundannahmen hergeleitet.
Dadurch wird sichergestellt, dass die Basis aller Entscheidungen dem Geimeinwohl dient
und nicht durch Traditionen oder zum Nutzen Priviligierter beeinflusst werden kann.

Der Schutz von Lebewesen und das Level des sicherzustellenden Wohlbefindens
ist abhängig von der jeweiligen Gattung
und wird gewichtet durch ihren Entwicklungsstand, insbesondere ihrer Intelligenz,
dem Populationsanteil in ihrem Lebensraum
sowie der genetischen bzw. biologischen Verwandtschaft zu den Gesellschaftsmitgliedern.

## Realisierung

Die Verwirklichung dieser Ideen in einem Supera Specios
erfordert neben entsprechenden Technologien zur Verwaltung
auch Strategien, um sich im Kapitalismus zu behaupten.
Dies wird in den folgenden beiden Kapiteln beschrieben.
