# Kapitalismus {#sec-situation-capitalism}

Wir leben im Kapitalismus.
Selbst sozialistische Staaten wie China, Nordkorea, Vietnam oder Kuba sind in die globale Marktwirtschaft eingebunden
und eigentlich eher kapitalistisch.
Zumindest kann nicht bestritten werden, dass jeder auf seine Weise nach Geld giert.

Wird man davon glücklich? In unserem System ganz klar: Ja.
Gesundheit, Spaß, Zeit.
Alles kostet Geld und die meiste Arbeit heute dient einzig der Vermehrung von selbigem.
Wenn man das Tauschmittel Geld nur oberflächlich betrachtet, macht es natürlich Sinn:
Als Jäger und Sammler konnten wir noch eigentumslos leben, alles wurde in der Gruppe aufgeteilt.
Später entwickelte man aber den Ackerbau und die Viehzucht, wurde sesshaft.
Bauern waren in der Lage mehr Nahrung zu produzieren als sie selbst benötigten, ihnen fehlten dafür aber andere Dinge;
der Tauschhandel begann.
Um die Suche nach einem Tauschpartner zu vereinfachen, sich von der u.&nbsp;U. geringen Haltbarkeit der Tauschgüter unabhängig zu machen
und die Frage nach dem Gegenwert zu verallgemeinern, wurden später möglichst seltene und lang haltbare Zwischentauschmittel eingeführt,
wie z.&nbsp;B. Kaurischneckenhäuser in China irgendwann zwischen dem 7. und 11. Jahrhundert vor Christus [@yungti_2003].
In der Folge wurden daraus Gold- und Silber-Münzen mit entsprechendem
Gegenwert^[Häufig war der Wert einer Münze etwas höher als die enthaltenen Metalle,
um den Herstellungsaufwand einzubeziehen und ein Wiedereinschmelzen unattraktiver zu machen.],
bis man sich schließlich von der Notwendigkeit eines Warenwertes trennte, wie es bei unserem heutigen Bar- und Buchgeld der Fall ist.
Das klingt zunächst wie eine perfekte Lösung.

Ein großes Problem ist die Verwaltung des Geldes.
Heutzutage wird es vermehrt ohne einen echten Gegenwert zu haben.
Durch das Zinssystem gibt es immer mehr Schulden als (virtuelles) Geld,
d.&nbsp;h. die ganze Welt kann den privatisierten Banken gegenüber insgesamt niemals schuldenfrei sein.
Großkonzerne und Banken haben Geld und demnach Macht über jeden, der Geld benötigt.
Nicht nur normale Bürger, auch die Regierungen gehören dazu.
Folglich bringt es rein gar nichts in die Politik zu gehen, wenn man etwas daran ändern möchte
-- die sogenannte "Elite", wie sie Verschwörungstheoretiker nennen, wird das verhindern.
Das ist nur leider keine Verschwörungstheorie sondern eine Tatsache.
Die genauen Verhältnisse kann man überall selbst nachlesen.

Ein weiteres entscheidendes Problem ist relativ jung.
Wir sind an einem Punkt angelangt, an dem wir die gesamte Welt problemlos versorgen könnten.
^[Siehe dazu auch die Ergebnisse des [Venus-Projektes](https://de.wikipedia.org/wiki/Jacque_Fresco#Das_Venus-Projekt).]
Doch alles was man zum Leben benötigt kostet Geld und Geld bekommt man nur durch Arbeit.
Wie schafft man sich Arbeit, wenn es eigentlich kaum welche geben muss? Man produziert billig und kurzlebig.
Man sorgt künstlich für Knappheit, denn was selten ist, ist wertvoll.
^[Recherchieren Sie dazu das Thema [Künstliche Knappheit](https://de.wikipedia.org/wiki/Künstliche_Knappheit).]
Darüberhinaus lässt man monotone und anspruchslose Arbeit von Menschen statt von Maschinen erledigen
um die Arbeitslosenzahlen niedrig zu halten, denn man braucht ja Arbeit, um zu leben
-- selbst wenn sie vollkommen sinnlos ist.
Effizienz, Reichhaltigkeit und Nachhaltigkeit widersprechen folglich der Struktur des profitorientierten Systemes.

Das Wohl eines Menschen darf demnach nicht davon abhängen, möglichst viel Profit zu erwirtschaften oder allgemein gesagt Probleme zu lösen,
denn sonst erzeugt er sie künstlich (wie Krieg oder Nahrungsmittelvernichtung).
