# Demokratie {#sec-situation-democracy}

Es wird allgemein behauptet, dass wir in einer Demokratie leben.
Tatsächlich haben wir aber kaum Einfluss auf Entscheidungen.
Der kleinste Anteil der Gesellschaft hat den größten Einfluss -
sowohl auf den Markt als auch auf die Politik.

Die Aufteilung von Entscheidungen in verschiedene Hierarchien hat mehrere Gründe:
Wenn lokale Probleme in kleineren Gruppen gelöst werden, verringert das die Komplexität.
Zudem können somit leichter regionale Meinungsunterschiede erlaubt werden.
Um nun keine Konflikte mit anderen Gruppierungen zu erzeugen,
muss es übergeordnete Instanzen geben, die die untergeordneten reglementieren.
Diese Macht wird natürlich so weit es geht ausgenutzt, um eigene Ziele zu bestärken.
Völlig klar.
Über den Zielen der Bürger stehen aber nicht nur die Ziele der Parteien,
die noch relativ nah an den Wünschen der Bürger liegen müssten,
denn schließlich wurden sie vom Volk gewählt.
Jede Instanz hat ihre Instanz darüber, die wieder eigene Ziele hat.
Durch psychologische Manipulationen, insbesondere über die Medien,
gibt es auch effektive Mittel, um diese Absichten zu verschleiern.
Dadurch können untergeordnete Instanzen -- vor allem normale Bürger --
dazu verleitet werden, diversen Initiativen aus dem falschen Bauchgefühl heraus zustimmen.
Ein gutes Beispiel ist der Terror-Hype.
Seine Folgen waren u.&nbsp;a. die Lockerung des Datenschutzes inkl. steigender Überwachung
oder die Aushebelung des deutschen Gesetzgebungsverfahrens durch den Vertrag von Lissabon.

Allzu direkt darf die Demokratie jedoch auch nicht sein.
Als einfacher Bürger kann man die Komplexität hinter den Entscheidungen gar nicht überblicken und handelt oft voreingenommen.
Die Aufgabe der Parteien und Lobbyisten ist es, komplizierte Sachverhalte zu analysieren
und Lösungen mit entsprechenden Begründungen vorzuschlagen, welche dann akzeptiert werden können oder nicht.
Entscheidungen beruhen also auf dem Vertrauen weniger Instanzen, welche dieses natürlich zu ihren Gunsten ausnutzen können.
