# Revolutionen {#sec-situation-revolutions}

Versuche, den von Karl Marx und Friedrich Engels prophezeiten Kommunismus durchzusetzen,
scheiterten bereits an der sozialisitischen Vorstufe und am Wirtschafts-Management.

Allgemein scheitern Revolutionsversuche, welche keine Diktatur hervorbringen wollen, an der Trägheit der Menschen.
Die an den wichtigen Positionen zu wohlhabende und allgemein müde Masse beginnt nicht auf Basis von systemfeindlichen Diskussionen,
sich rückhaltlos dem gewöhnlichem Alltag zu widersetzen, geschweige denn kollektiv und ausreichend konsequent.
Dies wäre existenzgefährdend.
Es müsste schon gewaltiges schief laufen, allerdings ist dies sehr unwahrscheinlich: Man will seine Sklaven schließlich behalten.
Die "Elite" wird uns füttern, gerade so viel, dass wir arbeiten können und mangels Alternativen auch arbeiten werden.

Den letzten Punkt kann man gut anhand eines Spielkasinos verdeutlichen:
Wir sind quasi die Spieler und die Politiker sind maximal die Croupiers.
Warum sollten die Besitzer des Kasinos -- Großkonzerne und Banken -- etwas an den Regeln ändern?
Oder gar das Kasino für alle freigeben? Es läuft für sie nunmal so wie es läuft.
