# Analyse {#sec-situation-analysis}

Wir stellen also fest:

- Eine profitorientierte oder ressourcen-arme Gesellschaft erzeugt Gier und damit Machtstreben.
    Ersteres bedingt der Kapitalismus und letzteres wird für ihn konstruiert.
- Allgemeingültige Selbstlosigkeit bzw. Solidarität ist nicht angeboren.
- Absolute Demokratie führt zu Chaos und benachteiligt Randgruppen;
    abgeschwächte Demokratie führt zum Kontrollverlust.
- Wir werden in unseren Handlungsmöglichkeiten immer weiter eingeschränkt.
    Schon jetzt sind wir Sklaven, aber noch arbeiten wir unter freiem Himmel.
- Wir sind technologisch so gut wie festgefahren.
    Noch länger auf einen Durchbruch zu warten, welcher uns zu einem besseren System befähigt, ist zu riskant.
- Die Organisation bzw. der Aufruf zu revolutionären Tätigkeiten darf nicht von einer Minderheit ausgehen.

Zusammenfassend kann man sagen, dass unser System grundlegende Widersprüche aufweist
und Änderungen im benötigen Maßstab in ihm nicht möglich sind; wählen gehen genügt nicht.
Man muss ganz von vorne beginnen.
Mit den politischen Mitteln, die uns zur Verfügung gestellt werden, kommen wir nicht weiter.
Die bloße Verteilung von aufklärenden Informationen genügt aber auch nicht.
